// Code generated by MockGen. DO NOT EDIT.
// Source: account_repo.go

// Package accrepository is a generated GoMock package.
package accrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	account "github.com/codepnw/go-starter-kit/internal/features/account"
	gomock "github.com/golang/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// FindAccountByID mocks base method.
func (m *MockAccountRepository) FindAccountByID(ctx context.Context, accountID int64) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccountByID", ctx, accountID)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccountByID indicates an expected call of FindAccountByID.
func (mr *MockAccountRepositoryMockRecorder) FindAccountByID(ctx, accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccountByID", reflect.TypeOf((*MockAccountRepository)(nil).FindAccountByID), ctx, accountID)
}

// FindAccountsByOwner mocks base method.
func (m *MockAccountRepository) FindAccountsByOwner(ctx context.Context, ownerID string) ([]*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccountsByOwner", ctx, ownerID)
	ret0, _ := ret[0].([]*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccountsByOwner indicates an expected call of FindAccountsByOwner.
func (mr *MockAccountRepositoryMockRecorder) FindAccountsByOwner(ctx, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccountsByOwner", reflect.TypeOf((*MockAccountRepository)(nil).FindAccountsByOwner), ctx, ownerID)
}

// InsertAccount mocks base method.
func (m *MockAccountRepository) InsertAccount(ctx context.Context, acc *account.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAccount", ctx, acc)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAccount indicates an expected call of InsertAccount.
func (mr *MockAccountRepositoryMockRecorder) InsertAccount(ctx, acc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAccount", reflect.TypeOf((*MockAccountRepository)(nil).InsertAccount), ctx, acc)
}

// InsertEntryTx mocks base method.
func (m *MockAccountRepository) InsertEntryTx(ctx context.Context, tx *sql.Tx, accountID, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEntryTx", ctx, tx, accountID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEntryTx indicates an expected call of InsertEntryTx.
func (mr *MockAccountRepositoryMockRecorder) InsertEntryTx(ctx, tx, accountID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEntryTx", reflect.TypeOf((*MockAccountRepository)(nil).InsertEntryTx), ctx, tx, accountID, amount)
}

// UpdateAccountBalanceTx mocks base method.
func (m *MockAccountRepository) UpdateAccountBalanceTx(ctx context.Context, tx *sql.Tx, accountID, balance int64) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountBalanceTx", ctx, tx, accountID, balance)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountBalanceTx indicates an expected call of UpdateAccountBalanceTx.
func (mr *MockAccountRepositoryMockRecorder) UpdateAccountBalanceTx(ctx, tx, accountID, balance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountBalanceTx", reflect.TypeOf((*MockAccountRepository)(nil).UpdateAccountBalanceTx), ctx, tx, accountID, balance)
}
