// Code generated by MockGen. DO NOT EDIT.
// Source: transfer_redis_repo.go

// Package transferrepository is a generated GoMock package.
package transferrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransferRedisRepository is a mock of TransferRedisRepository interface.
type MockTransferRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransferRedisRepositoryMockRecorder
}

// MockTransferRedisRepositoryMockRecorder is the mock recorder for MockTransferRedisRepository.
type MockTransferRedisRepositoryMockRecorder struct {
	mock *MockTransferRedisRepository
}

// NewMockTransferRedisRepository creates a new mock instance.
func NewMockTransferRedisRepository(ctrl *gomock.Controller) *MockTransferRedisRepository {
	mock := &MockTransferRedisRepository{ctrl: ctrl}
	mock.recorder = &MockTransferRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferRedisRepository) EXPECT() *MockTransferRedisRepositoryMockRecorder {
	return m.recorder
}

// CheckIdempotencyKey mocks base method.
func (m *MockTransferRedisRepository) CheckIdempotencyKey(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIdempotencyKey indicates an expected call of CheckIdempotencyKey.
func (mr *MockTransferRedisRepositoryMockRecorder) CheckIdempotencyKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIdempotencyKey", reflect.TypeOf((*MockTransferRedisRepository)(nil).CheckIdempotencyKey), ctx, key)
}

// DeleteIdempotencyKey mocks base method.
func (m *MockTransferRedisRepository) DeleteIdempotencyKey(ctx context.Context, idemKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIdempotencyKey", ctx, idemKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIdempotencyKey indicates an expected call of DeleteIdempotencyKey.
func (mr *MockTransferRedisRepositoryMockRecorder) DeleteIdempotencyKey(ctx, idemKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIdempotencyKey", reflect.TypeOf((*MockTransferRedisRepository)(nil).DeleteIdempotencyKey), ctx, idemKey)
}
