// Code generated by MockGen. DO NOT EDIT.
// Source: transfer_repo.go

// Package transferrepository is a generated GoMock package.
package transferrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	transfer "github.com/codepnw/go-starter-kit/internal/features/transfer"
	gomock "github.com/golang/mock/gomock"
)

// MockTransferRepository is a mock of TransferRepository interface.
type MockTransferRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransferRepositoryMockRecorder
}

// MockTransferRepositoryMockRecorder is the mock recorder for MockTransferRepository.
type MockTransferRepositoryMockRecorder struct {
	mock *MockTransferRepository
}

// NewMockTransferRepository creates a new mock instance.
func NewMockTransferRepository(ctrl *gomock.Controller) *MockTransferRepository {
	mock := &MockTransferRepository{ctrl: ctrl}
	mock.recorder = &MockTransferRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferRepository) EXPECT() *MockTransferRepositoryMockRecorder {
	return m.recorder
}

// InsertTransferTx mocks base method.
func (m *MockTransferRepository) InsertTransferTx(ctx context.Context, tx *sql.Tx, input *transfer.Transfer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransferTx", ctx, tx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransferTx indicates an expected call of InsertTransferTx.
func (mr *MockTransferRepositoryMockRecorder) InsertTransferTx(ctx, tx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransferTx", reflect.TypeOf((*MockTransferRepository)(nil).InsertTransferTx), ctx, tx, input)
}
